services:
    laravel-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/nginx/admin.conf:/etc/nginx/sites-available/admin.conf
            - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./docker/redis/redis.conf:/etc/redis/redis.conf
        ports:
            - "8000:80"
            - "6379:6379"
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_HOST=mysql
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
            - REDIS_HOST=127.0.0.1
            - REDIS_PORT=6379
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root_secret
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: laravel
            PMA_PASSWORD: secret
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
        driver: bridge
